from decimal import Decimal
from typing import Optional
from pydantic import BaseModel, Field
from models.Budget import Budget


class ExpenseDTO(BaseModel):
    """
    Data Transfer Object for Expense.
    Represents an expense item with its details.
    """
    name: Optional[str] = Field(None, description="Name of the expense item")
    owner: Optional[str] = Field(None, description="Owner or responsible person for the expense")
    account_number: Optional[str] = Field(None, description="Account number associated with the expense")
    amounts: Optional[list[Decimal]] = Field(None, description="List of amounts for each period")

class PeriodDTO(BaseModel):
    """
    Data Transfer Object for Period.
    Represents a budget period with its details and associated items.
    """
    planned_amount: Optional[Decimal] = Field(None, description="Planned amount for the period")
    name: Optional[str] = Field(None, description="Name of the period (e.g., 'Q1 2024')")
    expenses: Optional[list[ExpenseDTO]] = Field(None, description="List of expense items for this period")

class BudgetItemDTO(BaseModel):
    """
    Data Transfer Object for Budget Item.
    Represents a budget item with its details and associated expenses.
    """
    owner: Optional[str] = Field(None, description="Owner or responsible person for the budget item")
    name: Optional[str] = Field(None, description="Name of the budget item")
    account_number: Optional[str] = Field(None, description="Primary account number for the budget item")
    periods: Optional[list[PeriodDTO]] = Field(None, description="List of budget periods")
    period_names: Optional[list[str]] = Field(None, description="List of names for each budget period")
    # planned_amount_per_period: Optional[list[Decimal]] = Field(None, description="List of planned amounts for each period")
    summary: Optional[Decimal] = Field(None, description="Total budget amount across all periods")

class BudgetDTO(BaseModel):
    """
    Data Transfer Object for a list of Budgets.
    Represents a collection of budget items.
    """
    title: Optional[str] = Field(None, description="Title of the budget")
    description: Optional[str] = Field(None, description="Description of the budget")
    list_of_budget_items: list[BudgetItemDTO]  # Match the JSON structure from mock data

class ComplexBudgetDTO(BaseModel):
    """
    Data Transfer Object for Complex Budget.
    Represents a complex budget with additional features and details.
    """
    id: Optional[str] = Field(None, description="Unique identifier for the complex budget")
    period_names: list[str] = Field(..., description="List of headers for the budget")
    budget: BudgetDTO = Field(None, description="Budget details, if applicable")

    @classmethod
    def parse_from_BudgetDTO(cls, input: BudgetDTO) -> 'ComplexBudgetDTO':
        """
        Parse a BudgetDTO into a ComplexBudgetDTO object.

        Args:
            input: BudgetListDTO object containing the list of budgets
            
        Returns:
            ComplexBudgetDTO: A new instance of ComplexBudgetDTO
        
        Raises:
            ValueError: If the input budget list is empty
        """
        if not input or not input.list_of_budget_items:
            raise ValueError("Input budget list cannot be empty")

        # Get period names from the first budget (they should be the same for all budgets)
        period_names = input.list_of_budget_items[0].period_names if input.list_of_budget_items[0].period_names else []

        return cls(
            id=None,  # ID can be set later or generated by the database
            period_names=period_names,
            budget=input
        )

    @classmethod
    def parse_from_Budget(cls, input: Budget) -> 'ComplexBudgetDTO':
        """
        Parse a Budget object into a ComplexBudgetDTO object.

        Args:
            input: Budget object containing the budget details

        Returns:
            ComplexBudgetDTO: A new instance of ComplexBudgetDTO
        """
        if not input:
            raise ValueError("Input budget cannot be empty")

        # Adapt Budget (ORM) object to ComplexBudgetDTO structure
        return cls(
            id=input.get("id", None),
            period_names=input.get("period_names", []),
            budget=BudgetDTO(
                title=input.get("title", None),
                description=input.get("description", None),
                list_of_budget_items=[
                    BudgetItemDTO(
                        owner=item["owner_id"],
                        name=item["label"],
                        account_number=item["account_number"],
                        periods=[
                            PeriodDTO(
                                planned_amount=period["planned_amount"],
                                name=period["label"],
                                expenses=[
                                    ExpenseDTO(
                                        name=expense["name"],
                                        owner=expense.get("owner", None),
                                        account_number=expense.get("account_number", None),
                                        amounts=expense.get("amounts", [])
                                    ) for expense in period.get("expense_list", [])
                                ]
                            ) for period in item["periods"]
                    ],
                    period_names=[period["label"] for period in item["periods"]],
                    summary=item["summary"]
                ) for item in input["list_of_budget_items"]
            ] 
        )   
    )
